name: Build and Test Triton (AMD)

on:
  push:
    branches:
      - main-windows
  pull_request:
    branches:
      - main-windows
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: main-windows
      python_minor:
        description: Python minor version
        required: true
        type: string
        default: '12'
      pytest_args:
        description: pytest args
        required: true
        type: string
        default: '-n 8 -k "not test_kwargs and not test_load_scope_sem_coop_grid_cta_one and not test_sum_dtype"'

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    with:
      git_tag: ${{ inputs.git_tag }}

  build-and-test-triton:
    runs-on: triton-windows1
    env:
      PIP_CACHE_DIR: E:\pip-cache
      PYTHON_MINOR: ${{ inputs.python_minor || '12' }}
      PYTEST_ARGS: ${{ inputs.pytest_args || '-n 8 -k "not test_kwargs and not test_load_scope_sem_coop_grid_cta_one and not test_sum_dtype"' }}
    steps:
      - uses: astral-sh/setup-uv@v7

      - name: Clean caches
        shell: powershell
        run: |
          if (Test-Path -Path ~/.triton) { rm -r ~/.triton }
          if (Test-Path -Path triton-windows/build) { rm -r -Force triton-windows/build }
          if (Test-Path -Path triton-windows/python/build) { rm -r triton-windows/python/build }

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git_tag || '' }}
          path: triton-windows
          fetch-depth: 1

      - name: Create venv
        shell: powershell
        run: |
          uv venv .venv-cp3${{ env.PYTHON_MINOR }} --python 3.${{ env.PYTHON_MINOR }}.10 --clear
          .venv-cp3${{ env.PYTHON_MINOR }}\Scripts\activate.ps1
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - name: Build wheel
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Launch-VsDevShell.ps1" -Arch amd64
          .venv-cp3${{ env.PYTHON_MINOR }}\Scripts\activate.ps1
          python -m pip install --upgrade cibuildwheel

          cd triton-windows
          git rev-parse HEAD

          $Env:TRITON_BUILD_PROTON = "0"
          $Env:CIBW_BUILD = "{cp3${{ env.PYTHON_MINOR }}-win_amd64,}"
          $Env:CIBW_BUILD_VERBOSITY = "1"
          $Env:CIBW_ENABLE = "cpython-freethreading"
          if (Test-Path -Path wheelhouse) { rm wheelhouse/* }
          if (Test-Path -Path setup.py)
          {
            cibuildwheel .
          }
          else
          {
            cibuildwheel python
          }

      - name: Unit test
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Launch-VsDevShell.ps1" -Arch amd64
          .venv-cp3${{ env.PYTHON_MINOR }}\Scripts\activate.ps1
          python -m pip install --upgrade numpy pytest-xdist pytest-timeout scipy expecttest
          python -m pip install --index-url https://rocm.nightlies.amd.com/v2/gfx110X-all/ torch "rocm[libraries,devel]"
          cd triton-windows/wheelhouse
          python -m pip install $(Get-ChildItem | Select-Object -First 1)
          cd ../python/test/unit
          pytest ${{ env.PYTEST_ARGS }}
